sudo: required

language: ruby

services:
  - docker-compose

before_script:
  - cd Pathago
  - docker-compose up -d
  - sleep 5000
script:
  - docker-compose run app rake db:create
  - docker-compose run app rake db:migrate
  - echo "Done !!!"
  - sleep 2000
after_script:
  - docker-compose down
