sudo: required

language: ruby

services:
  - docker-compose

before_script:
  - cd Pathago
  - docker-compose up --build -d
script:
  - docker-compose run app rake db:create
  - docker-compose run app rake db:migrate
  - echo "Done !!!"
after_script:
  - docker-compose down
